import type { LoadedFile } from "../graph/build";
import type { SymbolRow } from "../db/schema";
import type { Architecture } from "../discover/types";
import type { Confidence, FindingDraft } from "../review/types";

type Draft = Omit<FindingDraft, "origin" | "confidence" | "verification"> & { confidence?: Confidence };

/** Deterministic findings derived from the repository model, not from AI. */
export function structuralFindings(files: LoadedFile[], symbols: SymbolRow[], arch: Architecture): FindingDraft[] {
  const out: FindingDraft[] = [];
  const src = files.filter((f) => !f.isExcluded && f.classification === "source" && !f.isTest);
  const push = (f: Draft) => out.push({ origin: "static", verification: "verified", analyzer: "brody-structure", ...f, confidence: f.confidence ?? "High" });

  for (const f of src.filter((f) => f.lines > 1000).sort((a, b) => b.lines - a.lines).slice(0, 8)) {
    push({ title: `Very large file (${f.lines} lines)`, category: "Maintainability", severity: f.lines > 2500 ? "Medium" : "Low", filePath: f.path, startLine: 1, endLine: f.lines, evidence: `${f.path} contains ${f.lines} lines and ${symbols.filter((s) => s.filePath === f.path).length} symbols.`, whatHappens: `The file holds ${f.lines} lines of code in a single module.`, whyItMatters: "Large files concentrate unrelated responsibilities, slow code review, increase merge conflicts and are harder to test in isolation.", businessImpact: "Higher cost and risk for every change made in this area.", remediation: "Split the file along responsibility boundaries (for example, data access, validation and orchestration).", verificationNote: "Computed from line counts." });
  }
  const bigFns = symbols.filter((s) => ["function", "method", "endpoint", "component", "hook"].includes(s.kind) && s.endLine - s.startLine + 1 > 150 && !files.find((f) => f.path === s.filePath)?.isTest).sort((a, b) => (b.endLine - b.startLine) - (a.endLine - a.startLine)).slice(0, 8);
  for (const s of bigFns) push({ title: `Very long ${s.kind}: ${s.qualifiedName} (${s.endLine - s.startLine + 1} lines)`, category: "Maintainability", severity: "Low", filePath: s.filePath, startLine: s.startLine, endLine: s.endLine, evidence: s.signature ?? s.name, whatHappens: `${s.qualifiedName} spans ${s.endLine - s.startLine + 1} lines.`, whyItMatters: "Long functions mix several steps, which hides bugs and makes unit testing difficult.", remediation: "Extract cohesive steps into named helper functions.", relatedComponents: [s.qualifiedName], verificationNote: "Computed from parsed symbol ranges." });
  const complex = symbols.filter((s) => Number((s.meta as { complexity?: number } | null)?.complexity ?? 0) >= 20 && !files.find((f) => f.path === s.filePath)?.isTest).sort((a, b) => Number((b.meta as { complexity: number }).complexity) - Number((a.meta as { complexity: number }).complexity)).slice(0, 8);
  for (const s of complex) { const c = Number((s.meta as { complexity: number }).complexity); push({ title: `High cyclomatic complexity in ${s.qualifiedName} (${c})`, category: "Maintainability", severity: c >= 40 ? "Medium" : "Low", filePath: s.filePath, startLine: s.startLine, endLine: s.endLine, evidence: `${s.signature ?? s.name} — ${c} independent branches counted by the parser.`, whatHappens: `The function contains about ${c} decision points (if/loops/case/catch/logical operators).`, whyItMatters: "Each decision path needs its own test; high branching correlates with defects and makes behaviour hard to reason about.", remediation: "Simplify with early returns, lookup tables or smaller functions, and add tests covering each branch.", relatedComponents: [s.qualifiedName], verificationNote: "Computed from the syntax tree." }); }

  // Duplicates
  const dupes = files.filter((f) => !f.isExcluded && f.duplicateOf && f.classification === "source");
  if (dupes.length) push({ title: `${dupes.length} byte-identical duplicate source file${dupes.length > 1 ? "s" : ""}`, category: "Maintainability", severity: "Low", filePath: dupes[0].path, evidence: dupes.slice(0, 6).map((d) => `${d.path} == ${d.duplicateOf}`).join("\n"), whatHappens: "Several source files have exactly the same content as another file.", whyItMatters: "Copies drift apart over time, so a fix applied to one is silently missing from the others.", remediation: "Keep a single copy and import it where needed.", verificationNote: "Detected by content hash equality." });

  // Testing
  const testCount = arch.tests.files.filter((t) => t.kind !== "fixture" && t.kind !== "mock" && t.kind !== "helper").length;
  if (src.length >= 5 && testCount === 0) push({ title: "No automated tests found", category: "Testing", severity: "High", whatHappens: `The repository has ${src.length} source files and no recognisable test files.`, whyItMatters: "Without tests, regressions are found by users instead of by the build, and refactoring is risky.", businessImpact: "Slower and riskier delivery; every release depends on manual verification.", remediation: "Add unit tests for the highest-importance modules first, then integration tests for the main request flows.", verificationNote: "No files matched test naming or directory conventions." });
  else if (src.length >= 10 && testCount > 0 && testCount / src.length < 0.1) push({ title: `Low test-to-source ratio (${testCount} test files for ${src.length} source files)`, category: "Testing", severity: "Medium", whatHappens: "Test files exist but cover a small fraction of the source.", whyItMatters: "Large parts of behaviour are unprotected against regression.", remediation: "Prioritise tests for the modules listed under untested critical components.", verificationNote: "Computed from file counts." });
  const untested = arch.tests.untestedCritical.slice(0, 8);
  if (untested.length >= 2 || (untested.length === 1 && testCount > 0)) {
    push({ title: `${untested.length} important file${untested.length > 1 ? "s have" : " has"} no tests`, category: "Testing", severity: untested.some((u) => /route|controller|api|auth|payment|billing|service/i.test(u.path)) ? "Medium" : "Low", confidence: "Medium", filePath: untested[0].path, startLine: 1, endLine: 1, evidence: untested.map((u) => u.path).join("\n"), whatHappens: "These files rank highest by how many other files depend on them, but no test imports them or calls their symbols.", whyItMatters: "Failures in highly depended-upon code propagate to many callers, and regressions here are not caught by the build.", remediation: "Add unit tests for the exported functions and failure paths of these files, starting with the request handlers and payment or data-access code.", relatedComponents: untested.map((u) => u.path), verificationNote: "Derived from TESTS relationships in the dependency graph; coverage through end-to-end tests would not be visible." });
  }
  // Authentication consistency across API routes
  const apiRoutes = arch.routes.filter((r) => r.kind === "api" && r.method !== "USE");
  const guarded = apiRoutes.filter((r) => r.auth === "authenticated");
  const open = apiRoutes.filter((r) => r.auth === "unknown");
  if (guarded.length > 0 && open.length > 0) {
    push({ title: `${open.length} API route${open.length > 1 ? "s show" : " shows"} no authentication check while ${guarded.length} other route${guarded.length > 1 ? "s do" : " does"}`, category: "Security", severity: "Medium", confidence: "Low", filePath: open[0].file, startLine: open[0].line, endLine: open[0].line, evidence: open.slice(0, 8).map((r) => `${r.method} ${r.path} (${r.file}:${r.line})`).join("\n"), whatHappens: `Some routes are protected by an authentication middleware or guard, but these routes have none visible at their definition: ${open.slice(0, 5).map((r) => `${r.method} ${r.path}`).join(", ")}.`, whyItMatters: "If these routes expose user or business data, callers can read or change it without signing in (missing access control). Authentication applied in shared middleware elsewhere would not be visible to this check.", businessImpact: "Potential unauthorised access to customer or order data.", remediation: "Confirm each route is intentionally public; otherwise apply the same authentication and authorization middleware used by the protected routes.", relatedComponents: open.slice(0, 8).map((r) => `${r.method} ${r.path}`), verificationNote: "Comparison of middleware visible on each route definition; global middleware registered elsewhere is not considered." });
  }
  if (apiRoutes.length >= 3 && guarded.length === 0 && !arch.externalServices.some((x) => x.category === "auth") && !arch.dependencies.some((d) => /^(next-auth|@auth\/|passport|jsonwebtoken|jose|@clerk\/|@auth0\/|express-jwt|lucia|better-auth|django-allauth|flask-login|authlib|python-jose|pyjwt)/i.test(d.name))) {
    push({ title: `None of the ${apiRoutes.length} API routes has an authentication check`, category: "Security", severity: "Low", confidence: "Low", filePath: apiRoutes[0].file, startLine: apiRoutes[0].line, endLine: apiRoutes[0].line, evidence: apiRoutes.slice(0, 6).map((r) => `${r.method} ${r.path} (${r.file}:${r.line})`).join("\n"), whatHappens: "No route has authentication middleware or guard, and no authentication library or provider was detected.", whyItMatters: "Anyone who can reach the service can call every route. That is acceptable for a local single-user tool but not for a shared or internet-facing deployment.", remediation: "Put the service behind an authenticating reverse proxy, or add authentication and authorization to the routes before exposing it.", verificationNote: "Checked middleware visible at each route definition and imports of common authentication libraries." });
  }
  // Operations
  const hasServer = arch.entryPoints.some((e) => e.kind === "web-server") || arch.routes.some((r) => r.kind === "api");
  if (hasServer && !arch.routes.some((r) => /health|ready|live|ping|status/i.test(r.path)) && !files.some((f) => f.text && /HEALTHCHECK|livenessProbe|readinessProbe/.test(f.text))) push({ title: "No health-check endpoint detected", category: "Operations", severity: "Low", confidence: "Medium", whatHappens: "The service exposes routes but none resemble a health, readiness or liveness endpoint.", whyItMatters: "Orchestrators and load balancers cannot tell a hung instance from a healthy one.", remediation: "Add a lightweight /health endpoint that checks critical dependencies.", verificationNote: "No route path contained health/ready/live/ping/status and no container probe was found." });
  if (!arch.infra.some((i) => ["GitHub Actions", "GitLab CI", "CircleCI", "Jenkins"].includes(i.kind)) && src.length >= 10) push({ title: "No CI configuration detected", category: "Operations", severity: "Low", confidence: "Medium", whatHappens: "No CI pipeline definition was found in the repository.", whyItMatters: "Tests, linting and builds are not enforced on every change.", remediation: "Add a CI workflow that runs tests, type checks and the production build.", verificationNote: "Looked for GitHub Actions, GitLab CI, CircleCI and Jenkins files." });
  const usedEnv = arch.envVars.filter((e) => e.files.length > 0);
  const undeclared = usedEnv.filter((e) => e.declaredIn.length === 0 && !/^(NODE_ENV|PORT|HOME|PATH|CI|PWD|USER|TZ|HOSTNAME|VERCEL.*|NEXT_RUNTIME|npm_.*|GITHUB_.*|RUNNER_.*)$/.test(e.name));
  if (undeclared.length >= 3 && !files.some((f) => /^\.env(\.example|\.sample|\.template)?$/.test(f.name))) push({ title: `${undeclared.length} environment variables are read but never documented`, category: "Operations", severity: "Low", confidence: "Medium", evidence: undeclared.slice(0, 10).map((e) => `${e.name} (${e.files[0].path}:${e.files[0].line})`).join("\n"), whatHappens: "Code reads environment variables that are not declared in any .env example, Dockerfile or compose file.", whyItMatters: "New environments fail at runtime with missing configuration, and operators have no reference list.", remediation: "Add an .env.example listing every variable with a description, and validate configuration at startup.", relatedComponents: undeclared.slice(0, 10).map((e) => e.name), verificationNote: "Derived from static scanning of environment access patterns." });
  if (!files.some((f) => !f.isExcluded && /^readme(\.[a-z]+)?$/i.test(f.name) && !f.path.includes("/"))) push({ title: "No top-level README", category: "Maintainability", severity: "Informational", confidence: "High", whatHappens: "The repository root has no README.", whyItMatters: "New contributors have no entry point for setup and orientation.", remediation: "Add a README describing purpose, setup and how to run tests.", verificationNote: "Checked root-level file names." });
  const manifestsWithoutLock = arch.dependencies.filter((d) => d.ecosystem === "npm" && !d.dev).length > 0 && !files.some((f) => /^(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?)$/.test(f.name));
  if (manifestsWithoutLock) push({ title: "npm dependencies are not locked", category: "Dependencies", severity: "Low", confidence: "Medium", whatHappens: "package.json declares dependencies but no lockfile was found.", whyItMatters: "Builds can resolve different versions over time, causing irreproducible failures and supply-chain exposure.", remediation: "Commit the lockfile and install with `npm ci` in CI.", verificationNote: "No lockfile in the analysed file set (it may have been excluded)." });
  const unpinned = arch.dependencies.filter((d) => d.ecosystem === "pypi" && !d.dev && !d.version && /requirements/.test(d.manifest)).length;
  if (unpinned >= 5) push({ title: `${unpinned} Python dependencies have no version constraint`, category: "Dependencies", severity: "Low", confidence: "Medium", whatHappens: "requirements files list packages without version specifiers.", whyItMatters: "Any new release, including a breaking or compromised one, is installed automatically.", remediation: "Pin versions (ideally with hashes) or use a lock file.", verificationNote: "Parsed from requirements files." });
  const wildcard = arch.dependencies.filter((d) => d.ecosystem === "npm" && (d.version === "*" || d.version === "latest"));
  if (wildcard.length) push({ title: `${wildcard.length} npm dependencies use "*" or "latest"`, category: "Dependencies", severity: "Medium", confidence: "High", evidence: wildcard.slice(0, 8).map((d) => `${d.name}: ${d.version}`).join("\n"), whatHappens: "Dependency ranges accept any version.", whyItMatters: "Untested or malicious releases are pulled in automatically.", remediation: "Use a bounded semver range and rely on the lockfile.", verificationNote: "Parsed from package.json." });

  // Secrets
  const byKind = new Map<string, Architecture["secrets"]>();
  for (const s of arch.secrets) { const l = byKind.get(s.path) ?? []; l.push(s); byKind.set(s.path, l); }
  for (const [p, list] of [...byKind.entries()].slice(0, 10)) {
    const f = files.find((x) => x.path === p);
    if (f?.isTest && list.every((s) => s.kind === "Password Assignment")) continue;
    const inTest = !!f?.isTest;
    push({ title: inTest ? `Secret-like value in test or fixture file ${p}` : `Likely secret committed in ${p}`, category: "Security", severity: inTest ? "Low" : list.some((s) => /Private Key|AWS|GitHub|Stripe|Anthropic|OpenAI|Connection String/.test(s.kind)) ? "Critical" : "High", confidence: inTest ? "Low" : "Medium", filePath: p, startLine: list[0].line, endLine: list[0].line, evidence: list.slice(0, 4).map((s) => `line ${s.line}: ${s.kind} ${s.preview}`).join("\n"), whatHappens: `Pattern matching found ${list.length} value(s) that look like credentials (${[...new Set(list.map((s) => s.kind))].join(", ")}). Values are redacted in this report.`, whyItMatters: "Credentials committed to a repository are visible to everyone with access and persist in git history even after deletion.", businessImpact: "Unauthorised access to the connected service and potential data exposure until the credential is rotated.", remediation: "Rotate the credential immediately, remove it from history, and load it from environment configuration or a secrets manager.", verificationNote: "Deterministic pattern match; entropy and context may still make it a false positive (for example test data)." });
  }
  // Architecture: layering (UI importing data layer directly)
  return out;
}
