/** Knowledge tables used by architecture detection. All matching is evidence based. */

export interface ServiceSignature {
  name: string;
  category: string;
  packages: string[];
  envPrefixes: string[];
  hosts: string[];
  purpose: string;
  failureImpact: string;
}

export const SERVICE_SIGNATURES: ServiceSignature[] = [
  { name: "Stripe", category: "payments", packages: ["stripe", "@stripe/stripe-js", "@stripe/react-stripe-js"], envPrefixes: ["STRIPE_"], hosts: ["api.stripe.com"], purpose: "payment processing and billing", failureImpact: "checkout, subscription and invoice operations fail" },
  { name: "PayPal", category: "payments", packages: ["@paypal/checkout-server-sdk", "paypalrestsdk", "@paypal/react-paypal-js"], envPrefixes: ["PAYPAL_"], hosts: ["api.paypal.com"], purpose: "payment processing", failureImpact: "payments cannot be collected" },
  { name: "AWS", category: "cloud", packages: ["aws-sdk", "@aws-sdk/client-s3", "@aws-sdk/client-sqs", "@aws-sdk/client-dynamodb", "@aws-sdk/client-ses", "@aws-sdk/client-lambda", "@aws-sdk/client-sns", "boto3", "botocore", "github.com/aws/aws-sdk-go", "github.com/aws/aws-sdk-go-v2", "software.amazon.awssdk", "com.amazonaws", "AWSSDK", "aws-sdk-s3", "aws-sdk-core", "aws-sdk-rails"], envPrefixes: ["AWS_"], hosts: ["amazonaws.com"], purpose: "cloud infrastructure (storage, queues, compute)", failureImpact: "object storage, queue or cloud API operations fail" },
  { name: "Google Cloud", category: "cloud", packages: ["@google-cloud/storage", "@google-cloud/pubsub", "@google-cloud/firestore", "google-cloud-storage", "google-cloud-pubsub", "google-cloud-bigquery", "cloud.google.com/go", "com.google.cloud"], envPrefixes: ["GOOGLE_CLOUD_", "GCP_", "GCLOUD_"], hosts: ["googleapis.com"], purpose: "cloud infrastructure", failureImpact: "cloud storage or messaging operations fail" },
  { name: "Azure", category: "cloud", packages: ["@azure/storage-blob", "@azure/identity", "azure-storage-blob", "azure-identity", "Azure.Storage.Blobs", "Azure.Identity"], envPrefixes: ["AZURE_"], hosts: ["azure.com", "windows.net"], purpose: "cloud infrastructure", failureImpact: "cloud storage or identity operations fail" },
  { name: "Supabase", category: "backend-platform", packages: ["@supabase/supabase-js", "@supabase/ssr", "@supabase/auth-helpers-nextjs", "supabase"], envPrefixes: ["SUPABASE_", "NEXT_PUBLIC_SUPABASE_"], hosts: ["supabase.co"], purpose: "hosted Postgres, auth and storage", failureImpact: "database access, authentication and file storage fail" },
  { name: "Firebase", category: "backend-platform", packages: ["firebase", "firebase-admin", "@react-native-firebase/app"], envPrefixes: ["FIREBASE_", "NEXT_PUBLIC_FIREBASE_"], hosts: ["firebaseio.com", "firebaseapp.com"], purpose: "hosted auth, database and push messaging", failureImpact: "authentication, realtime data and notifications fail" },
  { name: "OpenAI", category: "ai", packages: ["openai", "@ai-sdk/openai", "langchain_openai", "github.com/sashabaranov/go-openai", "com.theokanning.openai-gpt3-java"], envPrefixes: ["OPENAI_"], hosts: ["api.openai.com"], purpose: "language model inference and embeddings", failureImpact: "AI-generated features stop producing output" },
  { name: "Anthropic", category: "ai", packages: ["@anthropic-ai/sdk", "anthropic", "@ai-sdk/anthropic", "langchain_anthropic"], envPrefixes: ["ANTHROPIC_"], hosts: ["api.anthropic.com"], purpose: "language model inference", failureImpact: "AI-generated features stop producing output" },
  { name: "Google AI", category: "ai", packages: ["@google/generative-ai", "google-generativeai", "@ai-sdk/google", "google-genai"], envPrefixes: ["GEMINI_", "GOOGLE_AI_", "GOOGLE_GENERATIVE_AI_"], hosts: ["generativelanguage.googleapis.com"], purpose: "language model inference", failureImpact: "AI-generated features stop producing output" },
  { name: "Vercel AI Gateway", category: "ai", packages: ["ai", "@ai-sdk/gateway"], envPrefixes: ["AI_GATEWAY_"], hosts: ["ai-gateway.vercel.sh"], purpose: "model routing", failureImpact: "AI features fail" },
  { name: "Hugging Face", category: "ai", packages: ["@huggingface/inference", "transformers", "huggingface_hub", "sentence-transformers"], envPrefixes: ["HF_", "HUGGINGFACE_"], hosts: ["huggingface.co"], purpose: "model hosting and inference", failureImpact: "model downloads or inference fail" },
  { name: "Pinecone", category: "vector-db", packages: ["@pinecone-database/pinecone", "pinecone-client", "pinecone"], envPrefixes: ["PINECONE_"], hosts: ["pinecone.io"], purpose: "vector similarity search", failureImpact: "semantic search and retrieval fail" },
  { name: "Weaviate", category: "vector-db", packages: ["weaviate-client", "weaviate-ts-client"], envPrefixes: ["WEAVIATE_"], hosts: ["weaviate"], purpose: "vector similarity search", failureImpact: "semantic search fails" },
  { name: "Qdrant", category: "vector-db", packages: ["@qdrant/js-client-rest", "qdrant-client"], envPrefixes: ["QDRANT_"], hosts: ["qdrant"], purpose: "vector similarity search", failureImpact: "semantic search fails" },
  { name: "Chroma", category: "vector-db", packages: ["chromadb"], envPrefixes: ["CHROMA_"], hosts: [], purpose: "vector similarity search", failureImpact: "semantic search fails" },
  { name: "PostgreSQL", category: "database", packages: ["pg", "postgres", "pg-promise", "psycopg2", "psycopg2-binary", "psycopg", "asyncpg", "github.com/lib/pq", "github.com/jackc/pgx", "github.com/jackc/pgx/v5", "org.postgresql", "Npgsql", "@vercel/postgres", "@neondatabase/serverless", "pgvector"], envPrefixes: ["POSTGRES_", "PG", "DATABASE_URL"], hosts: [], purpose: "relational data storage", failureImpact: "all persisted reads and writes fail" },
  { name: "MySQL", category: "database", packages: ["mysql", "mysql2", "pymysql", "mysqlclient", "aiomysql", "github.com/go-sql-driver/mysql", "mysql-connector-java", "MySql.Data", "mysql2"], envPrefixes: ["MYSQL_"], hosts: [], purpose: "relational data storage", failureImpact: "all persisted reads and writes fail" },
  { name: "SQLite", category: "database", packages: ["better-sqlite3", "sqlite3", "sqlite", "aiosqlite", "github.com/mattn/go-sqlite3", "modernc.org/sqlite", "Microsoft.Data.Sqlite", "@libsql/client", "libsql"], envPrefixes: ["SQLITE_", "TURSO_"], hosts: [], purpose: "embedded relational storage", failureImpact: "persisted reads and writes fail" },
  { name: "MongoDB", category: "database", packages: ["mongodb", "mongoose", "pymongo", "motor", "go.mongodb.org/mongo-driver", "org.mongodb", "MongoDB.Driver", "mongoid"], envPrefixes: ["MONGO_", "MONGODB_"], hosts: ["mongodb.net"], purpose: "document data storage", failureImpact: "all persisted reads and writes fail" },
  { name: "Redis", category: "cache", packages: ["redis", "ioredis", "@upstash/redis", "aioredis", "github.com/redis/go-redis", "github.com/go-redis/redis", "io.lettuce", "redis.clients", "StackExchange.Redis", "connect-redis"], envPrefixes: ["REDIS_", "UPSTASH_REDIS_"], hosts: ["upstash.io"], purpose: "caching, sessions, queues and pub/sub", failureImpact: "cached reads, sessions or queued work fail depending on usage" },
  { name: "Elasticsearch / OpenSearch", category: "search", packages: ["@elastic/elasticsearch", "elasticsearch", "opensearch-py", "@opensearch-project/opensearch"], envPrefixes: ["ELASTIC", "OPENSEARCH_"], hosts: ["elastic-cloud.com"], purpose: "full-text search", failureImpact: "search queries fail" },
  { name: "Algolia", category: "search", packages: ["algoliasearch", "react-instantsearch"], envPrefixes: ["ALGOLIA_"], hosts: ["algolia.net"], purpose: "hosted search", failureImpact: "search queries fail" },
  { name: "Meilisearch", category: "search", packages: ["meilisearch"], envPrefixes: ["MEILI"], hosts: [], purpose: "full-text search", failureImpact: "search queries fail" },
  { name: "Kafka", category: "messaging", packages: ["kafkajs", "kafka-python", "confluent-kafka", "github.com/segmentio/kafka-go", "github.com/confluentinc/confluent-kafka-go", "org.apache.kafka", "Confluent.Kafka"], envPrefixes: ["KAFKA_"], hosts: [], purpose: "event streaming", failureImpact: "event publication and consumption stall" },
  { name: "RabbitMQ", category: "messaging", packages: ["amqplib", "pika", "aio-pika", "github.com/rabbitmq/amqp091-go", "github.com/streadway/amqp", "RabbitMQ.Client", "bunny"], envPrefixes: ["RABBITMQ_", "AMQP_"], hosts: [], purpose: "message queueing", failureImpact: "queued work stops being delivered" },
  { name: "BullMQ / Bull", category: "queue", packages: ["bullmq", "bull", "bee-queue"], envPrefixes: [], hosts: [], purpose: "Redis-backed job queue", failureImpact: "background jobs stop processing" },
  { name: "Celery", category: "queue", packages: ["celery"], envPrefixes: ["CELERY_"], hosts: [], purpose: "distributed task queue", failureImpact: "background tasks stop processing" },
  { name: "Sidekiq", category: "queue", packages: ["sidekiq"], envPrefixes: [], hosts: [], purpose: "background job processing", failureImpact: "background jobs stop processing" },
  { name: "Inngest", category: "queue", packages: ["inngest"], envPrefixes: ["INNGEST_"], hosts: ["inngest.com"], purpose: "durable background functions", failureImpact: "scheduled and event-driven functions stop" },
  { name: "Temporal", category: "workflow", packages: ["@temporalio/client", "@temporalio/worker", "temporalio", "go.temporal.io"], envPrefixes: ["TEMPORAL_"], hosts: [], purpose: "durable workflow orchestration", failureImpact: "workflows stop executing" },
  { name: "SendGrid", category: "email", packages: ["@sendgrid/mail", "sendgrid"], envPrefixes: ["SENDGRID_"], hosts: ["api.sendgrid.com"], purpose: "transactional email", failureImpact: "outbound email stops" },
  { name: "Resend", category: "email", packages: ["resend"], envPrefixes: ["RESEND_"], hosts: ["api.resend.com"], purpose: "transactional email", failureImpact: "outbound email stops" },
  { name: "Postmark", category: "email", packages: ["postmark"], envPrefixes: ["POSTMARK_"], hosts: ["api.postmarkapp.com"], purpose: "transactional email", failureImpact: "outbound email stops" },
  { name: "Mailgun", category: "email", packages: ["mailgun.js", "mailgun-js"], envPrefixes: ["MAILGUN_"], hosts: ["api.mailgun.net"], purpose: "transactional email", failureImpact: "outbound email stops" },
  { name: "SMTP (Nodemailer / smtplib)", category: "email", packages: ["nodemailer"], envPrefixes: ["SMTP_", "MAIL_"], hosts: [], purpose: "outbound email", failureImpact: "outbound email stops" },
  { name: "Twilio", category: "messaging", packages: ["twilio"], envPrefixes: ["TWILIO_"], hosts: ["api.twilio.com"], purpose: "SMS and voice", failureImpact: "SMS/voice notifications stop" },
  { name: "Slack", category: "messaging", packages: ["@slack/web-api", "@slack/bolt", "slack_sdk", "slack-sdk"], envPrefixes: ["SLACK_"], hosts: ["slack.com"], purpose: "chat notifications and integrations", failureImpact: "Slack notifications stop" },
  { name: "Discord", category: "messaging", packages: ["discord.js", "discord.py"], envPrefixes: ["DISCORD_"], hosts: ["discord.com"], purpose: "chat bot integration", failureImpact: "bot stops responding" },
  { name: "Auth0", category: "auth", packages: ["@auth0/nextjs-auth0", "auth0", "@auth0/auth0-react", "auth0-python"], envPrefixes: ["AUTH0_"], hosts: ["auth0.com"], purpose: "identity provider", failureImpact: "users cannot sign in" },
  { name: "Clerk", category: "auth", packages: ["@clerk/nextjs", "@clerk/clerk-sdk-node", "@clerk/backend"], envPrefixes: ["CLERK_", "NEXT_PUBLIC_CLERK_"], hosts: ["clerk.com"], purpose: "identity provider", failureImpact: "users cannot sign in" },
  { name: "NextAuth / Auth.js", category: "auth", packages: ["next-auth", "@auth/core", "@auth/prisma-adapter", "@auth/drizzle-adapter"], envPrefixes: ["NEXTAUTH_", "AUTH_"], hosts: [], purpose: "session-based authentication", failureImpact: "users cannot sign in" },
  { name: "Okta", category: "auth", packages: ["@okta/okta-sdk-nodejs", "@okta/okta-auth-js"], envPrefixes: ["OKTA_"], hosts: ["okta.com"], purpose: "identity provider", failureImpact: "users cannot sign in" },
  { name: "GitHub API", category: "developer-platform", packages: ["@octokit/rest", "octokit", "PyGithub", "github.com/google/go-github", "@octokit/core"], envPrefixes: ["GITHUB_", "GH_"], hosts: ["api.github.com"], purpose: "repository and identity integration", failureImpact: "GitHub-backed features fail" },
  { name: "Sentry", category: "observability", packages: ["@sentry/nextjs", "@sentry/node", "@sentry/react", "@sentry/browser", "sentry-sdk", "github.com/getsentry/sentry-go", "io.sentry", "Sentry", "sentry-ruby", "sentry-rails"], envPrefixes: ["SENTRY_", "NEXT_PUBLIC_SENTRY_"], hosts: ["sentry.io"], purpose: "error monitoring", failureImpact: "errors go unreported; application continues" },
  { name: "Datadog", category: "observability", packages: ["dd-trace", "datadog", "ddtrace", "@datadog/browser-rum", "github.com/DataDog/dd-trace-go"], envPrefixes: ["DD_", "DATADOG_"], hosts: ["datadoghq.com"], purpose: "metrics and tracing", failureImpact: "telemetry stops; application continues" },
  { name: "OpenTelemetry", category: "observability", packages: ["@opentelemetry/api", "@opentelemetry/sdk-node", "opentelemetry-api", "opentelemetry-sdk", "go.opentelemetry.io/otel", "io.opentelemetry"], envPrefixes: ["OTEL_"], hosts: [], purpose: "traces and metrics export", failureImpact: "telemetry stops; application continues" },
  { name: "New Relic", category: "observability", packages: ["newrelic"], envPrefixes: ["NEW_RELIC_"], hosts: ["newrelic.com"], purpose: "application monitoring", failureImpact: "telemetry stops" },
  { name: "Prometheus", category: "observability", packages: ["prom-client", "prometheus_client", "prometheus-client", "github.com/prometheus/client_golang"], envPrefixes: ["PROMETHEUS_"], hosts: [], purpose: "metrics exposition", failureImpact: "metrics are not scraped" },
  { name: "Segment", category: "analytics", packages: ["analytics-node", "@segment/analytics-node", "@segment/analytics-next", "analytics-python"], envPrefixes: ["SEGMENT_"], hosts: ["segment.io"], purpose: "product analytics", failureImpact: "analytics events are lost" },
  { name: "PostHog", category: "analytics", packages: ["posthog-js", "posthog-node", "posthog"], envPrefixes: ["POSTHOG_", "NEXT_PUBLIC_POSTHOG_"], hosts: ["posthog.com"], purpose: "product analytics and feature flags", failureImpact: "analytics and flags degrade" },
  { name: "Mixpanel", category: "analytics", packages: ["mixpanel", "mixpanel-browser"], envPrefixes: ["MIXPANEL_"], hosts: ["mixpanel.com"], purpose: "product analytics", failureImpact: "analytics events are lost" },
  { name: "Google Analytics", category: "analytics", packages: ["react-ga", "react-ga4", "@next/third-parties"], envPrefixes: ["GA_", "NEXT_PUBLIC_GA_"], hosts: ["google-analytics.com"], purpose: "web analytics", failureImpact: "analytics events are lost" },
  { name: "LaunchDarkly", category: "feature-flags", packages: ["launchdarkly-node-server-sdk", "@launchdarkly/node-server-sdk", "launchdarkly-server-sdk"], envPrefixes: ["LAUNCHDARKLY_", "LD_"], hosts: ["launchdarkly.com"], purpose: "feature flags", failureImpact: "flags fall back to defaults" },
  { name: "Cloudinary", category: "media", packages: ["cloudinary"], envPrefixes: ["CLOUDINARY_"], hosts: ["cloudinary.com"], purpose: "media storage and transformation", failureImpact: "image uploads and transforms fail" },
  { name: "Uploadthing", category: "media", packages: ["uploadthing", "@uploadthing/react"], envPrefixes: ["UPLOADTHING_"], hosts: [], purpose: "file uploads", failureImpact: "uploads fail" },
  { name: "Vercel Blob", category: "storage", packages: ["@vercel/blob"], envPrefixes: ["BLOB_"], hosts: [], purpose: "object storage", failureImpact: "file storage fails" },
  { name: "MinIO / S3-compatible", category: "storage", packages: ["minio"], envPrefixes: ["MINIO_", "S3_"], hosts: [], purpose: "object storage", failureImpact: "file storage fails" },
  { name: "Shopify", category: "commerce", packages: ["@shopify/shopify-api", "@shopify/admin-api-client", "ShopifyAPI"], envPrefixes: ["SHOPIFY_"], hosts: ["myshopify.com"], purpose: "commerce platform", failureImpact: "storefront and order sync fail" },
  { name: "Plaid", category: "fintech", packages: ["plaid", "react-plaid-link"], envPrefixes: ["PLAID_"], hosts: ["plaid.com"], purpose: "bank account linking", failureImpact: "financial data sync fails" },
  { name: "Mapbox", category: "maps", packages: ["mapbox-gl", "react-map-gl"], envPrefixes: ["MAPBOX_", "NEXT_PUBLIC_MAPBOX_"], hosts: ["mapbox.com"], purpose: "maps", failureImpact: "map rendering fails" },
  { name: "Google Maps", category: "maps", packages: ["@react-google-maps/api", "@googlemaps/js-api-loader", "googlemaps"], envPrefixes: ["GOOGLE_MAPS_", "NEXT_PUBLIC_GOOGLE_MAPS_"], hosts: ["maps.googleapis.com"], purpose: "maps and geocoding", failureImpact: "map features fail" },
  { name: "Cloudflare", category: "cloud", packages: ["@cloudflare/workers-types", "cloudflare", "wrangler"], envPrefixes: ["CLOUDFLARE_", "CF_"], hosts: ["cloudflare.com"], purpose: "edge compute, storage and CDN", failureImpact: "edge functions or storage fail" },
  { name: "Vercel", category: "hosting", packages: ["@vercel/analytics", "@vercel/speed-insights", "@vercel/kv", "@vercel/edge-config", "@vercel/functions"], envPrefixes: ["VERCEL_", "KV_", "EDGE_CONFIG"], hosts: ["vercel.app"], purpose: "hosting and platform services", failureImpact: "platform features degrade" },
  { name: "Docker Registry", category: "infra", packages: [], envPrefixes: ["DOCKER_"], hosts: ["docker.io", "ghcr.io"], purpose: "container images", failureImpact: "deployments cannot pull images" },
  { name: "Ollama", category: "ai", packages: ["ollama", "@ai-sdk/ollama", "ollama-ai-provider"], envPrefixes: ["OLLAMA_"], hosts: ["localhost:11434"], purpose: "local model inference", failureImpact: "AI features fail" },
  { name: "Cohere", category: "ai", packages: ["cohere-ai", "cohere"], envPrefixes: ["COHERE_"], hosts: ["api.cohere.ai"], purpose: "embeddings and reranking", failureImpact: "retrieval quality degrades or fails" },
  { name: "Replicate", category: "ai", packages: ["replicate"], envPrefixes: ["REPLICATE_"], hosts: ["api.replicate.com"], purpose: "hosted model inference", failureImpact: "AI features fail" },
  { name: "LangChain", category: "ai-framework", packages: ["langchain", "@langchain/core", "@langchain/openai", "langchain-core", "langchain-community", "langgraph", "@langchain/langgraph"], envPrefixes: ["LANGCHAIN_", "LANGSMITH_"], hosts: [], purpose: "LLM orchestration framework", failureImpact: "n/a (library)" },
  { name: "LlamaIndex", category: "ai-framework", packages: ["llamaindex", "llama-index", "llama_index"], envPrefixes: [], hosts: [], purpose: "retrieval framework", failureImpact: "n/a (library)" },
];

export interface FrameworkSignature {
  name: string;
  category: string;
  packages: string[];
}

export const FRAMEWORK_SIGNATURES: FrameworkSignature[] = [
  { name: "Next.js", category: "frontend-framework", packages: ["next"] },
  { name: "React", category: "ui-library", packages: ["react", "react-dom"] },
  { name: "Vue", category: "ui-library", packages: ["vue"] },
  { name: "Nuxt", category: "frontend-framework", packages: ["nuxt"] },
  { name: "Svelte / SvelteKit", category: "frontend-framework", packages: ["svelte", "@sveltejs/kit"] },
  { name: "Angular", category: "frontend-framework", packages: ["@angular/core"] },
  { name: "Remix", category: "frontend-framework", packages: ["@remix-run/react", "@remix-run/node"] },
  { name: "Astro", category: "frontend-framework", packages: ["astro"] },
  { name: "Vite", category: "build-tool", packages: ["vite"] },
  { name: "Webpack", category: "build-tool", packages: ["webpack"] },
  { name: "Tailwind CSS", category: "styling", packages: ["tailwindcss"] },
  { name: "shadcn/ui / Radix", category: "ui-components", packages: ["@radix-ui/react-dialog", "@radix-ui/react-slot", "radix-ui"] },
  { name: "Material UI", category: "ui-components", packages: ["@mui/material"] },
  { name: "Chakra UI", category: "ui-components", packages: ["@chakra-ui/react"] },
  { name: "Redux", category: "state-management", packages: ["redux", "@reduxjs/toolkit", "react-redux"] },
  { name: "Zustand", category: "state-management", packages: ["zustand"] },
  { name: "Jotai", category: "state-management", packages: ["jotai"] },
  { name: "MobX", category: "state-management", packages: ["mobx"] },
  { name: "TanStack Query", category: "data-fetching", packages: ["@tanstack/react-query", "react-query"] },
  { name: "SWR", category: "data-fetching", packages: ["swr"] },
  { name: "tRPC", category: "api-framework", packages: ["@trpc/server", "@trpc/client"] },
  { name: "GraphQL", category: "api-framework", packages: ["graphql", "@apollo/server", "apollo-server", "@apollo/client", "graphql-yoga", "type-graphql", "strawberry-graphql", "graphene", "ariadne", "github.com/99designs/gqlgen", "com.graphql-java"] },
  { name: "Express", category: "backend-framework", packages: ["express"] },
  { name: "Fastify", category: "backend-framework", packages: ["fastify"] },
  { name: "Koa", category: "backend-framework", packages: ["koa"] },
  { name: "Hono", category: "backend-framework", packages: ["hono"] },
  { name: "NestJS", category: "backend-framework", packages: ["@nestjs/core", "@nestjs/common"] },
  { name: "Hapi", category: "backend-framework", packages: ["@hapi/hapi"] },
  { name: "Django", category: "backend-framework", packages: ["django", "Django"] },
  { name: "Django REST Framework", category: "api-framework", packages: ["djangorestframework", "rest_framework"] },
  { name: "Flask", category: "backend-framework", packages: ["flask", "Flask"] },
  { name: "FastAPI", category: "backend-framework", packages: ["fastapi"] },
  { name: "Starlette", category: "backend-framework", packages: ["starlette"] },
  { name: "Tornado", category: "backend-framework", packages: ["tornado"] },
  { name: "aiohttp", category: "backend-framework", packages: ["aiohttp"] },
  { name: "Ruby on Rails", category: "backend-framework", packages: ["rails", "railties"] },
  { name: "Sinatra", category: "backend-framework", packages: ["sinatra"] },
  { name: "Spring Boot", category: "backend-framework", packages: ["org.springframework.boot", "org.springframework", "spring-boot-starter-web", "spring-boot-starter"] },
  { name: "Micronaut", category: "backend-framework", packages: ["io.micronaut"] },
  { name: "Quarkus", category: "backend-framework", packages: ["io.quarkus"] },
  { name: "Ktor", category: "backend-framework", packages: ["io.ktor"] },
  { name: "ASP.NET Core", category: "backend-framework", packages: ["Microsoft.AspNetCore", "Microsoft.AspNetCore.App", "Microsoft.AspNetCore.Mvc"] },
  { name: "Gin", category: "backend-framework", packages: ["github.com/gin-gonic/gin"] },
  { name: "Echo", category: "backend-framework", packages: ["github.com/labstack/echo", "github.com/labstack/echo/v4"] },
  { name: "Fiber", category: "backend-framework", packages: ["github.com/gofiber/fiber", "github.com/gofiber/fiber/v2"] },
  { name: "Chi", category: "backend-framework", packages: ["github.com/go-chi/chi", "github.com/go-chi/chi/v5"] },
  { name: "Gorilla Mux", category: "backend-framework", packages: ["github.com/gorilla/mux"] },
  { name: "gRPC", category: "api-framework", packages: ["@grpc/grpc-js", "grpcio", "google.golang.org/grpc", "io.grpc", "Grpc.AspNetCore"] },
  { name: "Actix", category: "backend-framework", packages: ["actix-web"] },
  { name: "Axum", category: "backend-framework", packages: ["axum"] },
  { name: "Rocket", category: "backend-framework", packages: ["rocket"] },
  { name: "Laravel", category: "backend-framework", packages: ["laravel/framework"] },
  { name: "Symfony", category: "backend-framework", packages: ["symfony/framework-bundle", "symfony/symfony"] },
  { name: "Prisma", category: "orm", packages: ["prisma", "@prisma/client"] },
  { name: "Drizzle ORM", category: "orm", packages: ["drizzle-orm"] },
  { name: "TypeORM", category: "orm", packages: ["typeorm"] },
  { name: "Sequelize", category: "orm", packages: ["sequelize"] },
  { name: "Knex", category: "query-builder", packages: ["knex"] },
  { name: "Kysely", category: "query-builder", packages: ["kysely"] },
  { name: "Mongoose", category: "orm", packages: ["mongoose"] },
  { name: "SQLAlchemy", category: "orm", packages: ["sqlalchemy", "SQLAlchemy", "sqlmodel"] },
  { name: "Django ORM", category: "orm", packages: ["django"] },
  { name: "Alembic", category: "migrations", packages: ["alembic"] },
  { name: "Tortoise ORM", category: "orm", packages: ["tortoise-orm"] },
  { name: "Peewee", category: "orm", packages: ["peewee"] },
  { name: "GORM", category: "orm", packages: ["gorm.io/gorm", "github.com/jinzhu/gorm"] },
  { name: "sqlc", category: "query-builder", packages: ["github.com/sqlc-dev/sqlc"] },
  { name: "Hibernate / JPA", category: "orm", packages: ["org.hibernate", "jakarta.persistence", "javax.persistence", "spring-boot-starter-data-jpa"] },
  { name: "Entity Framework", category: "orm", packages: ["Microsoft.EntityFrameworkCore"] },
  { name: "Dapper", category: "orm", packages: ["Dapper"] },
  { name: "ActiveRecord", category: "orm", packages: ["activerecord"] },
  { name: "Diesel", category: "orm", packages: ["diesel"] },
  { name: "SQLx", category: "query-builder", packages: ["sqlx"] },
  { name: "Eloquent", category: "orm", packages: ["illuminate/database"] },
  { name: "Zod", category: "validation", packages: ["zod"] },
  { name: "Pydantic", category: "validation", packages: ["pydantic"] },
  { name: "Joi", category: "validation", packages: ["joi"] },
  { name: "Yup", category: "validation", packages: ["yup"] },
  { name: "Jest", category: "testing", packages: ["jest", "@jest/core", "ts-jest"] },
  { name: "Vitest", category: "testing", packages: ["vitest"] },
  { name: "Mocha", category: "testing", packages: ["mocha"] },
  { name: "Playwright", category: "testing", packages: ["@playwright/test", "playwright"] },
  { name: "Cypress", category: "testing", packages: ["cypress"] },
  { name: "Testing Library", category: "testing", packages: ["@testing-library/react", "@testing-library/dom"] },
  { name: "pytest", category: "testing", packages: ["pytest"] },
  { name: "unittest", category: "testing", packages: ["unittest"] },
  { name: "JUnit", category: "testing", packages: ["org.junit", "junit", "org.junit.jupiter"] },
  { name: "xUnit / NUnit", category: "testing", packages: ["xunit", "NUnit", "Microsoft.NET.Test.Sdk"] },
  { name: "RSpec", category: "testing", packages: ["rspec", "rspec-rails"] },
  { name: "Go testing", category: "testing", packages: ["testing", "github.com/stretchr/testify"] },
  { name: "Storybook", category: "tooling", packages: ["@storybook/react", "storybook"] },
  { name: "ESLint", category: "tooling", packages: ["eslint"] },
  { name: "TypeScript", category: "tooling", packages: ["typescript"] },
  { name: "Ruff", category: "tooling", packages: ["ruff"] },
  { name: "mypy", category: "tooling", packages: ["mypy"] },
  { name: "Docker", category: "infrastructure", packages: [] },
  { name: "Socket.IO", category: "realtime", packages: ["socket.io", "socket.io-client", "python-socketio"] },
  { name: "WebSockets (ws)", category: "realtime", packages: ["ws", "websockets"] },
  { name: "Electron", category: "desktop", packages: ["electron"] },
  { name: "React Native / Expo", category: "mobile", packages: ["react-native", "expo"] },
  { name: "Commander / yargs (CLI)", category: "cli", packages: ["commander", "yargs", "oclif", "@oclif/core", "cac"] },
  { name: "Click / Typer (CLI)", category: "cli", packages: ["click", "typer"] },
  { name: "Cobra (CLI)", category: "cli", packages: ["github.com/spf13/cobra"] },
  { name: "Clap (CLI)", category: "cli", packages: ["clap"] },
  { name: "Pandas / NumPy", category: "data-science", packages: ["pandas", "numpy"] },
  { name: "PyTorch", category: "ml", packages: ["torch"] },
  { name: "TensorFlow", category: "ml", packages: ["tensorflow"] },
  { name: "scikit-learn", category: "ml", packages: ["scikit-learn", "sklearn"] },
  { name: "Streamlit", category: "frontend-framework", packages: ["streamlit"] },
  { name: "Gradio", category: "frontend-framework", packages: ["gradio"] },
  { name: "Turborepo", category: "monorepo", packages: ["turbo"] },
  { name: "Nx", category: "monorepo", packages: ["nx"] },
];

/** Environment variables that imply sensitive content. */
export const SENSITIVE_ENV = /(SECRET|TOKEN|PASSWORD|PASSWD|PRIVATE|CREDENTIAL|API_KEY|APIKEY|ACCESS_KEY|SIGNING|DSN|_KEY$|_URL$|CONNECTION)/i;

/** Directory / keyword hints for functional areas. */
export const AREA_HINTS: { match: RegExp; name: string; description: string }[] = [
  { match: /(^|\/)(auth|authentication|authn|authz|login|session|sessions|oauth|sso|identity|accounts?)(\/|$)/i, name: "Authentication & Identity", description: "Sign-in, session handling, tokens and access control." },
  { match: /(^|\/)(payments?|billing|checkout|invoices?|subscriptions?|stripe|pricing)(\/|$)/i, name: "Payments & Billing", description: "Payment collection, subscriptions and invoicing." },
  { match: /(^|\/)(users?|profiles?|members?|customers?|people|contacts?)(\/|$)/i, name: "User Profiles", description: "User records, profiles and account management." },
  { match: /(^|\/)(notifications?|email|emails|mail|mailer|mailers|sms|push|alerts?)(\/|$)/i, name: "Notifications", description: "Email, SMS, push and in-app notifications." },
  { match: /(^|\/)(ingest|ingestion|import|importer|importers|crawl|crawler|crawlers|scrap(er|ers|ing)|collectors?|feeds?|etl|pipelines?|loaders?)(\/|$)/i, name: "Content Ingestion", description: "Collecting and importing data from external sources." },
  { match: /(^|\/)(search|indexing|indexer|retrieval|embeddings?)(\/|$)/i, name: "Search & Retrieval", description: "Indexing and querying content." },
  { match: /(^|\/)(rank|ranking|recommend|recommendations?|scoring|personalization)(\/|$)/i, name: "Ranking & Recommendations", description: "Ordering and recommending content." },
  { match: /(^|\/)(admin|administration|backoffice|dashboard|internal)(\/|$)/i, name: "Administration", description: "Administrative tooling and internal dashboards." },
  { match: /(^|\/)(reports?|reporting|analytics|metrics|insights|stats)(\/|$)/i, name: "Reporting & Analytics", description: "Aggregations, reporting and analytics." },
  { match: /(^|\/)(ai|llm|agents?|prompts?|ml|models_ai|openai|anthropic|inference|rag|chat|assistant)(\/|$)/i, name: "AI Processing", description: "Language-model prompts, agents and inference." },
  { match: /(^|\/)(jobs?|workers?|tasks?|queue|queues|cron|scheduler|schedulers|background)(\/|$)/i, name: "Background Jobs", description: "Asynchronous and scheduled work." },
  { match: /(^|\/)(api|routes?|controllers?|handlers?|endpoints?|resolvers?|graphql|rpc|trpc)(\/|$)/i, name: "API Layer", description: "HTTP/RPC endpoints and request handling." },
  { match: /(^|\/)(components?|ui|views?|pages?|screens?|layouts?|widgets?|templates?|frontend|client|web|app\/\(.*\)|hooks?|stores?|features?)(\/|$)/i, name: "User Interface", description: "Pages, components and client-side state." },
  { match: /(^|\/)(db|database|models?|schema|schemas|entities|migrations?|repositories|repository|prisma|orm|dal|persistence|data)(\/|$)/i, name: "Data Layer", description: "Schemas, models, migrations and data access." },
  { match: /(^|\/)(services?|domain|core|business|logic|usecases?|use_cases|application|managers?)(\/|$)/i, name: "Core Services", description: "Business logic and orchestration." },
  { match: /(^|\/)(middleware|middlewares|guards?|interceptors?|filters?|plugins?)(\/|$)/i, name: "Middleware", description: "Cross-cutting request processing." },
  { match: /(^|\/)(config|configs|configuration|settings|env)(\/|$)/i, name: "Configuration", description: "Runtime configuration and settings." },
  { match: /(^|\/)(utils?|utilities|helpers?|lib|libs|common|shared|pkg|internal\/util|toolkit|support)(\/|$)/i, name: "Shared Utilities", description: "Reusable helpers and shared code." },
  { match: /(^|\/)(infra|infrastructure|deploy|deployment|docker|k8s|kubernetes|terraform|helm|ops|devops|\.github|ci|scripts?|bin|tools?)(\/|$)/i, name: "Infrastructure & Deployment", description: "Build, deployment and operations." },
  { match: /(^|\/)(tests?|__tests__|spec|specs|e2e|cypress|fixtures?|__mocks__|testing)(\/|$)/i, name: "Testing", description: "Automated tests, fixtures and mocks." },
  { match: /(^|\/)(docs?|documentation|wiki|guides?)(\/|$)/i, name: "Documentation", description: "Project documentation." },
  { match: /(^|\/)(storage|files?|uploads?|media|assets|images?)(\/|$)/i, name: "File & Media Storage", description: "Uploads and stored media." },
  { match: /(^|\/)(events?|messaging|pubsub|streams?|kafka|webhooks?)(\/|$)/i, name: "Events & Messaging", description: "Event publication and consumption." },
  { match: /(^|\/)(orders?|cart|inventory|products?|catalog|shop|store)(\/|$)/i, name: "Commerce", description: "Products, carts, orders and inventory." },
  { match: /(^|\/)(i18n|locales?|translations?|intl)(\/|$)/i, name: "Internationalization", description: "Translations and locale handling." },
  { match: /(^|\/)(cache|caching)(\/|$)/i, name: "Caching", description: "Cached data and invalidation." },
  { match: /(^|\/)(security|crypto|encryption|permissions?|rbac|acl|policies)(\/|$)/i, name: "Security & Permissions", description: "Authorization policies and cryptography." },
];
